name: bx_mobile
description: "SaaS Mobile Suite modular e offline-first para o ecossistema Bexio ERP."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Icons & Design System
  cupertino_icons: ^1.0.8

  # Local Storage & Security (AES-256 Offline-First)
  path: ^1.9.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0

  # Networking & API Integration (Bexio Sandbox & REST API)
  dio: ^5.4.0

  # QR Code Scanner (Onboarding Phase 2)
  mobile_scanner: ^5.0.0

  # Utilities & Helpers
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
